### ISSUE TITLE
Empty bottomBar and middleBar still show up in Safari 

### ISSUE THREAD

**Issue by aliciatang** [Polymer/core-toolbar#25]
I used the following markup, it shows up properly in chrome but not in safari.
```html
<core-toolbar>
      <core-icon-button icon="menu"></core-icon-button>
      <span flex>title</span>
      <core-icon-button icon="translate"></core-icon-button>
      <core-icon-button icon="mail"></core-icon-button>
</core-toolbar>
```
After inspect in safari, find that although there is no elements in side bottomBar and middleBar it still take places and result in topBar has a huge margin on top.

I think the buttomBar and middleBar should be added to the shadow dom only if the user intend to used or at least remain hidden when no children elements.

**Comment by attilapeter** [comment]
+1

**Comment by frankiefu** [comment]
It seems to work fine for me on Safari.
https://gist.github.com/frankiefu/7e989e413a8febafd871

Do you have a testcase showing the issue?

**Comment by attilapeter** [comment]
Thanks, Frankie. It was my bad. Your gist file helped to identify the issue.

I could not see anything obvious until I realized that the <!doctype html> declaration was missing in my source. Safari ended up rendering a css without absolute positioning rule for the bottomBar and middleBar. These were defined as position: relative.

**Comment by aliciatang** [comment]
Thanks Frankie and attilapeter,
Yes, I've tried to add the <!doctype html>, and it indeed solve the problem in sofari.
Thanks a lot.
Alicia
